// Generated by AshTypescript - RPC Actions
// Do not edit this file manually


import type { AshRpcError, ConditionalPaginatedResultMixed, InferResult, SessionFilterInput, SessionResourceSchema, SessionSortField, SortString, UUID, UnifiedFieldSelection, UtcDateTimeUsec, ValidationResult } from "./ash_types";
export type * from "./ash_types";

// Helper Functions

/**
 * Configuration options for action RPC requests
 */
export interface ActionConfig {
  // Request data
  input?: Record<string, any>;
  identity?: any;
  fields?: Array<string | Record<string, any>>; // Field selection
  filter?: Record<string, any>; // Filter options (for reads)
  sort?: string | string[]; // Sort options
  page?:
    | {
        // Offset-based pagination
        limit?: number;
        offset?: number;
        count?: boolean;
      }
    | {
        // Keyset pagination
        limit?: number;
        after?: string;
        before?: string;
      };

  // Metadata
  metadataFields?: ReadonlyArray<string>;

  // HTTP customization
  headers?: Record<string, string>; // Custom headers
  fetchOptions?: RequestInit; // Fetch options (signal, cache, etc.)
  customFetch?: (
    input: RequestInfo | URL,
    init?: RequestInit,
  ) => Promise<Response>;

  // Multitenancy
  tenant?: string; // Tenant parameter

  // Hook context
  hookCtx?: Record<string, any>;
}

/**
 * Configuration options for validation RPC requests
 */
export interface ValidationConfig {
  // Request data
  input?: Record<string, any>;

  // HTTP customization
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (
    input: RequestInfo | URL,
    init?: RequestInit,
  ) => Promise<Response>;

  // Hook context
  hookCtx?: Record<string, any>;
}




/**
 * Gets the CSRF token from the page's meta tag
 * Returns null if no CSRF token is found
 */
export function getPhoenixCSRFToken(): string | null {
  return document
    ?.querySelector("meta[name='csrf-token']")
    ?.getAttribute("content") || null;
}

/**
 * Builds headers object with CSRF token for Phoenix applications
 * Returns headers object with X-CSRF-Token (if available)
 */
export function buildCSRFHeaders(headers: Record<string, string> = {}): Record<string, string> {
  const csrfToken = getPhoenixCSRFToken();
  if (csrfToken) {
    headers["X-CSRF-Token"] = csrfToken;
  }

  return headers;
}

/**
 * Internal helper function for making action RPC requests
 * Handles hooks, request configuration, fetch execution, and error handling
 * @param config Configuration matching ActionConfig
 */
export async function executeActionRpcRequest<T>(
  payload: Record<string, any>,
  config: ActionConfig
): Promise<T> {
    const processedConfig = config;

  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    ...processedConfig.headers,
    ...config.headers,
  };

  const fetchFunction = config.customFetch || processedConfig.customFetch || fetch;
  const fetchOptions: RequestInit = {
    ...processedConfig.fetchOptions,
    ...config.fetchOptions,
    method: "POST",
    headers,
    body: JSON.stringify(payload),
  };

  const response = await fetchFunction("/rpc/run", fetchOptions);
  const result = response.ok ? await response.json() : null;


  if (!response.ok) {
    return {
      success: false,
      errors: [
        {
          type: "network_error",
          message: `Network request failed: ${response.statusText}`,
          shortMessage: "Network error",
          vars: { statusCode: response.status, statusText: response.statusText },
          fields: [],
          path: [],
          details: { statusCode: response.status }
        }
      ],
    } as T;
  }

  return result as T;
}


/**
 * Internal helper function for making validation RPC requests
 * Handles hooks, request configuration, fetch execution, and error handling
 * @param config Configuration matching ValidationConfig
 */
export async function executeValidationRpcRequest<T>(
  payload: Record<string, any>,
  config: ValidationConfig
): Promise<T> {
    const processedConfig = config;

  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    ...processedConfig.headers,
    ...config.headers,
  };

  const fetchFunction = config.customFetch || processedConfig.customFetch || fetch;
  const fetchOptions: RequestInit = {
    ...processedConfig.fetchOptions,
    ...config.fetchOptions,
    method: "POST",
    headers,
    body: JSON.stringify(payload),
  };

  const response = await fetchFunction("/rpc/validate", fetchOptions);
  const result = response.ok ? await response.json() : null;


  if (!response.ok) {
    return {
      success: false,
      errors: [
        {
          type: "network_error",
          message: `Network request failed: ${response.statusText}`,
          shortMessage: "Network error",
          vars: { statusCode: response.status, statusText: response.statusText },
          fields: [],
          path: [],
          details: { statusCode: response.status }
        }
      ],
    } as T;
  }

  return result as T;
}







export type DeleteEntryInput = {
  path: string;
};

export type DeleteEntryFields = UnifiedFieldSelection<{path: string, __type: "TypedMap", __primitiveFields: "path"}>[];

export type InferDeleteEntryResult<
  Fields extends DeleteEntryFields | undefined,
> = InferResult<{path: string, __type: "TypedMap", __primitiveFields: "path"}, Fields>;

export type DeleteEntryResult<Fields extends DeleteEntryFields | undefined = undefined> = | { success: true; data: InferDeleteEntryResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on FileSystem
 *
 * @ashActionType :action
 */
export async function deleteEntry<Fields extends DeleteEntryFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: DeleteEntryInput;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<DeleteEntryResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "delete_entry",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<DeleteEntryResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on FileSystem
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateDeleteEntry(
  config: {
  tenant?: string;
  input: DeleteEntryInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "delete_entry",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ListDirectoryInput = {
  path: string;
};

export type ListDirectoryFields = UnifiedFieldSelection<{path: string, parent: string | null, entries: Array<{name: string, type: string, symlink: boolean, size: number, mtime: UtcDateTimeUsec | null, __type: "TypedMap", __primitiveFields: "name" | "type" | "symlink" | "size" | "mtime"}>, __type: "TypedMap", __primitiveFields: "path" | "parent"}>[];

export type InferListDirectoryResult<
  Fields extends ListDirectoryFields | undefined,
> = InferResult<{path: string, parent: string | null, entries: Array<{name: string, type: string, symlink: boolean, size: number, mtime: UtcDateTimeUsec | null, __type: "TypedMap", __primitiveFields: "name" | "type" | "symlink" | "size" | "mtime"}>, __type: "TypedMap", __primitiveFields: "path" | "parent"}, Fields>;

export type ListDirectoryResult<Fields extends ListDirectoryFields | undefined = undefined> = | { success: true; data: InferListDirectoryResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on FileSystem
 *
 * @ashActionType :action
 */
export async function listDirectory<Fields extends ListDirectoryFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: ListDirectoryInput;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ListDirectoryResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "list_directory",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<ListDirectoryResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on FileSystem
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateListDirectory(
  config: {
  tenant?: string;
  input: ListDirectoryInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_directory",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ListFilesInput = {
  path: string;
};

export type ListFilesFields = UnifiedFieldSelection<{root: string, files: Array<string>, truncated: boolean, __type: "TypedMap", __primitiveFields: "root" | "files" | "truncated"}>[];

export type InferListFilesResult<
  Fields extends ListFilesFields | undefined,
> = InferResult<{root: string, files: Array<string>, truncated: boolean, __type: "TypedMap", __primitiveFields: "root" | "files" | "truncated"}, Fields>;

export type ListFilesResult<Fields extends ListFilesFields | undefined = undefined> = | { success: true; data: InferListFilesResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on FileSystem
 *
 * @ashActionType :action
 */
export async function listFiles<Fields extends ListFilesFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: ListFilesInput;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ListFilesResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "list_files",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<ListFilesResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on FileSystem
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateListFiles(
  config: {
  tenant?: string;
  input: ListFilesInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_files",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ReadFileInput = {
  path: string;
  maxBytes?: number | null;
};

export type ReadFileFields = UnifiedFieldSelection<{path: string, size: number, truncated: boolean, binary: boolean, content: string | null, __type: "TypedMap", __primitiveFields: "path" | "size" | "truncated" | "binary" | "content"}>[];

export type InferReadFileResult<
  Fields extends ReadFileFields | undefined,
> = InferResult<{path: string, size: number, truncated: boolean, binary: boolean, content: string | null, __type: "TypedMap", __primitiveFields: "path" | "size" | "truncated" | "binary" | "content"}, Fields>;

export type ReadFileResult<Fields extends ReadFileFields | undefined = undefined> = | { success: true; data: InferReadFileResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on FileSystem
 *
 * @ashActionType :action
 */
export async function readFile<Fields extends ReadFileFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: ReadFileInput;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ReadFileResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "read_file",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<ReadFileResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on FileSystem
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateReadFile(
  config: {
  tenant?: string;
  input: ReadFileInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "read_file",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type SavePastedFileInput = {
  name: string;
  contentBase64: string;
};

export type SavePastedFileFields = UnifiedFieldSelection<{path: string, size: number, __type: "TypedMap", __primitiveFields: "path" | "size"}>[];

export type InferSavePastedFileResult<
  Fields extends SavePastedFileFields | undefined,
> = InferResult<{path: string, size: number, __type: "TypedMap", __primitiveFields: "path" | "size"}, Fields>;

export type SavePastedFileResult<Fields extends SavePastedFileFields | undefined = undefined> = | { success: true; data: InferSavePastedFileResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on FileSystem
 *
 * @ashActionType :action
 */
export async function savePastedFile<Fields extends SavePastedFileFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: SavePastedFileInput;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<SavePastedFileResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "save_pasted_file",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<SavePastedFileResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on FileSystem
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateSavePastedFile(
  config: {
  tenant?: string;
  input: SavePastedFileInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "save_pasted_file",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type WriteFileInput = {
  path: string;
  content: string;
};

export type WriteFileFields = UnifiedFieldSelection<{path: string, size: number, __type: "TypedMap", __primitiveFields: "path" | "size"}>[];

export type InferWriteFileResult<
  Fields extends WriteFileFields | undefined,
> = InferResult<{path: string, size: number, __type: "TypedMap", __primitiveFields: "path" | "size"}, Fields>;

export type WriteFileResult<Fields extends WriteFileFields | undefined = undefined> = | { success: true; data: InferWriteFileResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on FileSystem
 *
 * @ashActionType :action
 */
export async function writeFile<Fields extends WriteFileFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: WriteFileInput;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<WriteFileResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "write_file",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<WriteFileResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on FileSystem
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateWriteFile(
  config: {
  tenant?: string;
  input: WriteFileInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "write_file",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GitApplyPatchInput = {
  path: string;
  patch: string;
  target: "index" | "workdir";
};

export type GitApplyPatchFields = UnifiedFieldSelection<{applied: boolean, __type: "TypedMap", __primitiveFields: "applied"}>[];

export type InferGitApplyPatchResult<
  Fields extends GitApplyPatchFields | undefined,
> = InferResult<{applied: boolean, __type: "TypedMap", __primitiveFields: "applied"}, Fields>;

export type GitApplyPatchResult<Fields extends GitApplyPatchFields | undefined = undefined> = | { success: true; data: InferGitApplyPatchResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Git
 *
 * @ashActionType :action
 */
export async function gitApplyPatch<Fields extends GitApplyPatchFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: GitApplyPatchInput;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GitApplyPatchResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "git_apply_patch",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<GitApplyPatchResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Git
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateGitApplyPatch(
  config: {
  tenant?: string;
  input: GitApplyPatchInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "git_apply_patch",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GitBranchesInput = {
  path: string;
};

export type GitBranchesFields = UnifiedFieldSelection<{current: string | null, local: Array<{name: string, current: boolean, __type: "TypedMap", __primitiveFields: "name" | "current"}>, remote: Array<{name: string, current: boolean, __type: "TypedMap", __primitiveFields: "name" | "current"}>, __type: "TypedMap", __primitiveFields: "current"}>[];

export type InferGitBranchesResult<
  Fields extends GitBranchesFields | undefined,
> = InferResult<{current: string | null, local: Array<{name: string, current: boolean, __type: "TypedMap", __primitiveFields: "name" | "current"}>, remote: Array<{name: string, current: boolean, __type: "TypedMap", __primitiveFields: "name" | "current"}>, __type: "TypedMap", __primitiveFields: "current"}, Fields>;

export type GitBranchesResult<Fields extends GitBranchesFields | undefined = undefined> = | { success: true; data: InferGitBranchesResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Git
 *
 * @ashActionType :action
 */
export async function gitBranches<Fields extends GitBranchesFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: GitBranchesInput;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GitBranchesResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "git_branches",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<GitBranchesResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Git
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateGitBranches(
  config: {
  tenant?: string;
  input: GitBranchesInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "git_branches",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GitCheckoutInput = {
  path: string;
  name: string;
};

export type InferGitCheckoutResult = boolean;

export type GitCheckoutResult = | { success: true; data: InferGitCheckoutResult; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Git
 *
 * @ashActionType :action
 */
export async function gitCheckout(
  config: {
  tenant?: string;
  input: GitCheckoutInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GitCheckoutResult> {
  const payload = {
    action: "git_checkout",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeActionRpcRequest<GitCheckoutResult>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Git
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateGitCheckout(
  config: {
  tenant?: string;
  input: GitCheckoutInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "git_checkout",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GitCommitInput = {
  path: string;
  message: string;
  amend?: boolean | null;
};

export type GitCommitFields = UnifiedFieldSelection<{hash: string, __type: "TypedMap", __primitiveFields: "hash"}>[];

export type InferGitCommitResult<
  Fields extends GitCommitFields | undefined,
> = InferResult<{hash: string, __type: "TypedMap", __primitiveFields: "hash"}, Fields>;

export type GitCommitResult<Fields extends GitCommitFields | undefined = undefined> = | { success: true; data: InferGitCommitResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Git
 *
 * @ashActionType :action
 */
export async function gitCommit<Fields extends GitCommitFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: GitCommitInput;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GitCommitResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "git_commit",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<GitCommitResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Git
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateGitCommit(
  config: {
  tenant?: string;
  input: GitCommitInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "git_commit",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GitDiffInput = {
  path: string;
  file: string;
};

export type GitDiffFields = UnifiedFieldSelection<{diff: string, binary: boolean, truncated: boolean, __type: "TypedMap", __primitiveFields: "diff" | "binary" | "truncated"}>[];

export type InferGitDiffResult<
  Fields extends GitDiffFields | undefined,
> = InferResult<{diff: string, binary: boolean, truncated: boolean, __type: "TypedMap", __primitiveFields: "diff" | "binary" | "truncated"}, Fields>;

export type GitDiffResult<Fields extends GitDiffFields | undefined = undefined> = | { success: true; data: InferGitDiffResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Git
 *
 * @ashActionType :action
 */
export async function gitDiff<Fields extends GitDiffFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: GitDiffInput;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GitDiffResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "git_diff",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<GitDiffResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Git
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateGitDiff(
  config: {
  tenant?: string;
  input: GitDiffInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "git_diff",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GitDiscardInput = {
  path: string;
  file: string;
};

export type InferGitDiscardResult = boolean;

export type GitDiscardResult = | { success: true; data: InferGitDiscardResult; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Git
 *
 * @ashActionType :action
 */
export async function gitDiscard(
  config: {
  tenant?: string;
  input: GitDiscardInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GitDiscardResult> {
  const payload = {
    action: "git_discard",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeActionRpcRequest<GitDiscardResult>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Git
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateGitDiscard(
  config: {
  tenant?: string;
  input: GitDiscardInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "git_discard",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GitFileAtInput = {
  path: string;
  rev: string;
  file: string;
};

export type GitFileAtFields = UnifiedFieldSelection<{content: string, binary: boolean, truncated: boolean, missing: boolean, __type: "TypedMap", __primitiveFields: "content" | "binary" | "truncated" | "missing"}>[];

export type InferGitFileAtResult<
  Fields extends GitFileAtFields | undefined,
> = InferResult<{content: string, binary: boolean, truncated: boolean, missing: boolean, __type: "TypedMap", __primitiveFields: "content" | "binary" | "truncated" | "missing"}, Fields>;

export type GitFileAtResult<Fields extends GitFileAtFields | undefined = undefined> = | { success: true; data: InferGitFileAtResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Git
 *
 * @ashActionType :action
 */
export async function gitFileAt<Fields extends GitFileAtFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: GitFileAtInput;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GitFileAtResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "git_file_at",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<GitFileAtResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Git
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateGitFileAt(
  config: {
  tenant?: string;
  input: GitFileAtInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "git_file_at",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GitLogInput = {
  path: string;
  limit?: number | null;
};

export type GitLogFields = UnifiedFieldSelection<{commits: Array<{hash: string, author: string, date: string, subject: string, __type: "TypedMap", __primitiveFields: "hash" | "author" | "date" | "subject"}>, __type: "TypedMap", __primitiveFields: never}>[];

export type InferGitLogResult<
  Fields extends GitLogFields | undefined,
> = InferResult<{commits: Array<{hash: string, author: string, date: string, subject: string, __type: "TypedMap", __primitiveFields: "hash" | "author" | "date" | "subject"}>, __type: "TypedMap", __primitiveFields: never}, Fields>;

export type GitLogResult<Fields extends GitLogFields | undefined = undefined> = | { success: true; data: InferGitLogResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Git
 *
 * @ashActionType :action
 */
export async function gitLog<Fields extends GitLogFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: GitLogInput;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GitLogResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "git_log",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<GitLogResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Git
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateGitLog(
  config: {
  tenant?: string;
  input: GitLogInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "git_log",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GitShowInput = {
  path: string;
  hash: string;
};

export type GitShowFields = UnifiedFieldSelection<{text: string, truncated: boolean, __type: "TypedMap", __primitiveFields: "text" | "truncated"}>[];

export type InferGitShowResult<
  Fields extends GitShowFields | undefined,
> = InferResult<{text: string, truncated: boolean, __type: "TypedMap", __primitiveFields: "text" | "truncated"}, Fields>;

export type GitShowResult<Fields extends GitShowFields | undefined = undefined> = | { success: true; data: InferGitShowResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Git
 *
 * @ashActionType :action
 */
export async function gitShow<Fields extends GitShowFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: GitShowInput;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GitShowResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "git_show",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<GitShowResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Git
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateGitShow(
  config: {
  tenant?: string;
  input: GitShowInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "git_show",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GitStageInput = {
  path: string;
  file: string;
};

export type InferGitStageResult = boolean;

export type GitStageResult = | { success: true; data: InferGitStageResult; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Git
 *
 * @ashActionType :action
 */
export async function gitStage(
  config: {
  tenant?: string;
  input: GitStageInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GitStageResult> {
  const payload = {
    action: "git_stage",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeActionRpcRequest<GitStageResult>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Git
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateGitStage(
  config: {
  tenant?: string;
  input: GitStageInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "git_stage",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GitStatusInput = {
  path: string;
};

export type GitStatusFields = UnifiedFieldSelection<{repo: boolean, root: string | null, branch: string | null, files: Array<{path: string, status: string, staged: boolean, unstaged: boolean, __type: "TypedMap", __primitiveFields: "path" | "status" | "staged" | "unstaged"}>, __type: "TypedMap", __primitiveFields: "repo" | "root" | "branch"}>[];

export type InferGitStatusResult<
  Fields extends GitStatusFields | undefined,
> = InferResult<{repo: boolean, root: string | null, branch: string | null, files: Array<{path: string, status: string, staged: boolean, unstaged: boolean, __type: "TypedMap", __primitiveFields: "path" | "status" | "staged" | "unstaged"}>, __type: "TypedMap", __primitiveFields: "repo" | "root" | "branch"}, Fields>;

export type GitStatusResult<Fields extends GitStatusFields | undefined = undefined> = | { success: true; data: InferGitStatusResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Git
 *
 * @ashActionType :action
 */
export async function gitStatus<Fields extends GitStatusFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: GitStatusInput;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GitStatusResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "git_status",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<GitStatusResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Git
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateGitStatus(
  config: {
  tenant?: string;
  input: GitStatusInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "git_status",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GitUnstageInput = {
  path: string;
  file: string;
};

export type InferGitUnstageResult = boolean;

export type GitUnstageResult = | { success: true; data: InferGitUnstageResult; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Git
 *
 * @ashActionType :action
 */
export async function gitUnstage(
  config: {
  tenant?: string;
  input: GitUnstageInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GitUnstageResult> {
  const payload = {
    action: "git_unstage",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeActionRpcRequest<GitUnstageResult>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Git
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateGitUnstage(
  config: {
  tenant?: string;
  input: GitUnstageInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "git_unstage",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type CloseSessionInput = {
  id: UUID;
};

export type InferCloseSessionResult = boolean;

export type CloseSessionResult = | { success: true; data: InferCloseSessionResult; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Session
 *
 * @ashActionType :action
 */
export async function closeSession(
  config: {
  tenant?: string;
  input: CloseSessionInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<CloseSessionResult> {
  const payload = {
    action: "close_session",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeActionRpcRequest<CloseSessionResult>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Session
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateCloseSession(
  config: {
  tenant?: string;
  input: CloseSessionInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "close_session",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type CreateSessionInput = {
  scrollbackLimit?: number;
  name?: string | null;
  shell?: string | null;
  cwd?: string | null;
};

export type CreateSessionFields = UnifiedFieldSelection<SessionResourceSchema>[];

export type InferCreateSessionResult<
  Fields extends CreateSessionFields | undefined,
> = InferResult<SessionResourceSchema, Fields>;

export type CreateSessionResult<Fields extends CreateSessionFields | undefined = undefined> = | { success: true; data: InferCreateSessionResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Create a new Session
 *
 * @ashActionType :create
 */
export async function createSession<Fields extends CreateSessionFields | undefined = undefined>(
  config: {
  tenant?: string;
  input?: CreateSessionInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<CreateSessionResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "create_session",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<CreateSessionResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Create a new Session
 *
 * @ashActionType :create
 * @validation true
 */
export async function validateCreateSession(
  config: {
  tenant?: string;
  input?: CreateSessionInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "create_session",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type DeleteSessionResult = | { success: true; data: {}; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Delete a Session
 *
 * @ashActionType :destroy
 */
export async function deleteSession(
  config: {
  tenant?: string;
  identity: UUID;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<DeleteSessionResult> {
  const payload = {
    action: "delete_session",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeActionRpcRequest<DeleteSessionResult>(
    payload,
    config
  );
}


/**
 * Validate: Delete a Session
 *
 * @ashActionType :destroy
 * @validation true
 */
export async function validateDeleteSession(
  config: {
  tenant?: string;
  identity: UUID | string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "delete_session",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ListSessionsFields = UnifiedFieldSelection<SessionResourceSchema>[];


export type InferListSessionsResult<
  Fields extends ListSessionsFields | undefined,
  Page extends ListSessionsConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<SessionResourceSchema, Fields>>, {
  results: Array<InferResult<SessionResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<SessionResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type ListSessionsConfig = {
  tenant?: string;
  fields: ListSessionsFields;
  filter?: SessionFilterInput;
  sort?: SortString<SessionSortField> | SortString<SessionSortField>[];
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type ListSessionsResult<Fields extends ListSessionsFields, Page extends ListSessionsConfig["page"] = undefined> = | { success: true; data: InferListSessionsResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Session records
 *
 * @ashActionType :read
 */
export async function listSessions<Fields extends ListSessionsFields, Config extends ListSessionsConfig = ListSessionsConfig>(
  config: Config & { fields: Fields }
): Promise<ListSessionsResult<Fields, Config["page"]>> {
  const payload = {
    action: "list_sessions",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<ListSessionsResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


/**
 * Validate: Read Session records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListSessions(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_sessions",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type RenameSessionInput = {
  name?: string;
};

export type RenameSessionFields = UnifiedFieldSelection<SessionResourceSchema>[];

export type InferRenameSessionResult<
  Fields extends RenameSessionFields | undefined,
> = InferResult<SessionResourceSchema, Fields>;

export type RenameSessionResult<Fields extends RenameSessionFields | undefined = undefined> = | { success: true; data: InferRenameSessionResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Session
 *
 * @ashActionType :update
 */
export async function renameSession<Fields extends RenameSessionFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUID;
  input: RenameSessionInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<RenameSessionResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "rename_session",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<RenameSessionResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Session
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateRenameSession(
  config: {
  tenant?: string;
  identity: UUID | string;
  input: RenameSessionInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "rename_session",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type RestartSessionInput = {
  id: UUID;
};

export type InferRestartSessionResult = boolean;

export type RestartSessionResult = | { success: true; data: InferRestartSessionResult; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Session
 *
 * @ashActionType :action
 */
export async function restartSession(
  config: {
  tenant?: string;
  input: RestartSessionInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<RestartSessionResult> {
  const payload = {
    action: "restart_session",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeActionRpcRequest<RestartSessionResult>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Session
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateRestartSession(
  config: {
  tenant?: string;
  input: RestartSessionInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "restart_session",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type SetScrollbackLimitInput = {
  scrollbackLimit?: number;
};

export type SetScrollbackLimitFields = UnifiedFieldSelection<SessionResourceSchema>[];

export type InferSetScrollbackLimitResult<
  Fields extends SetScrollbackLimitFields | undefined,
> = InferResult<SessionResourceSchema, Fields>;

export type SetScrollbackLimitResult<Fields extends SetScrollbackLimitFields | undefined = undefined> = | { success: true; data: InferSetScrollbackLimitResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Session
 *
 * @ashActionType :update
 */
export async function setScrollbackLimit<Fields extends SetScrollbackLimitFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUID;
  input?: SetScrollbackLimitInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<SetScrollbackLimitResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "set_scrollback_limit",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<SetScrollbackLimitResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Session
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateSetScrollbackLimit(
  config: {
  tenant?: string;
  identity: UUID | string;
  input?: SetScrollbackLimitInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "set_scrollback_limit",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ApplyUpdateFields = UnifiedFieldSelection<{updatedTo: string, __type: "TypedMap", __primitiveFields: "updatedTo"}>[];

export type InferApplyUpdateResult<
  Fields extends ApplyUpdateFields | undefined,
> = InferResult<{updatedTo: string, __type: "TypedMap", __primitiveFields: "updatedTo"}, Fields>;

export type ApplyUpdateResult<Fields extends ApplyUpdateFields | undefined = undefined> = | { success: true; data: InferApplyUpdateResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Updater
 *
 * @ashActionType :action
 */
export async function applyUpdate<Fields extends ApplyUpdateFields | undefined = undefined>(
  config: {
  tenant?: string;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ApplyUpdateResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "apply_update",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<ApplyUpdateResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Updater
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateApplyUpdate(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "apply_update",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type CheckUpdateFields = UnifiedFieldSelection<{enabled: boolean, current: string, latest: string | null, tag: string | null, updateAvailable: boolean, notesUrl: string | null, __type: "TypedMap", __primitiveFields: "enabled" | "current" | "latest" | "tag" | "updateAvailable" | "notesUrl"}>[];

export type InferCheckUpdateResult<
  Fields extends CheckUpdateFields | undefined,
> = InferResult<{enabled: boolean, current: string, latest: string | null, tag: string | null, updateAvailable: boolean, notesUrl: string | null, __type: "TypedMap", __primitiveFields: "enabled" | "current" | "latest" | "tag" | "updateAvailable" | "notesUrl"}, Fields>;

export type CheckUpdateResult<Fields extends CheckUpdateFields | undefined = undefined> = | { success: true; data: InferCheckUpdateResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Execute generic action on Updater
 *
 * @ashActionType :action
 */
export async function checkUpdate<Fields extends CheckUpdateFields | undefined = undefined>(
  config: {
  tenant?: string;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<CheckUpdateResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "check_update",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<CheckUpdateResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Execute generic action on Updater
 *
 * @ashActionType :action
 * @validation true
 */
export async function validateCheckUpdate(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "check_update",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}

