#!/usr/bin/env bash
#
# Dala installer - downloads the native release for this machine and runs it
# as a user daemon (systemd on Linux, launchd on macOS).
#
#   curl -fsSL https://raw.githubusercontent.com/mjason/dala/main/install.sh | bash
#   ./install.sh [vX.Y.Z]        # specific version (default: latest)
set -euo pipefail

REPO="${DALA_REPO:-mjason/dala}"
ROOT="${DALA_HOME:-$HOME/.local/dala}"
DATA_DIR="${DALA_DATA_DIR:-$HOME/.local/share/dala}"
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/dala"
ENV_FILE="$CONFIG_DIR/dala.env"
CONFIG_FILE="$CONFIG_DIR/config.jsonc"
PORT="${DALA_PORT:-4400}"

say() { printf '\033[1;32m==>\033[0m %s\n' "$*"; }
die() { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

verify_checksum() {
  checksum_file=$1
  archive=$2
  asset=$3

  # Release checksums are a one-line sha256sum record. Reject missing,
  # ambiguous, or differently named records before invoking the checker so a
  # valid checksum for another file cannot authorize this archive.
  parsed=$(awk '
    { count++ }
    NF == 2 {
      name = $2
      sub(/^\*/, "", name)
      sub(/\r$/, "", name)
      print $1 "\t" name
      valid++
    }
    END { if (count != 1 || valid != 1) exit 1 }
  ' "$checksum_file") || die "malformed checksum for $asset"

  expected_hash=${parsed%%$'\t'*}
  expected_name=${parsed#*$'\t'}
  printf '%s\n' "$expected_hash" | grep -Eq '^[[:xdigit:]]{64}$' ||
    die "malformed checksum for $asset"
  [ "$expected_name" = "$asset" ] || die "checksum names unexpected asset"

  if [ "$PLATFORM" = "macos-arm64" ]; then
    (cd "$(dirname "$archive")" && shasum -a 256 -c "$(basename "$checksum_file")" >/dev/null) ||
      die "checksum mismatch"
  else
    (cd "$(dirname "$archive")" && sha256sum -c -- "$(basename "$checksum_file")" >/dev/null) ||
      die "checksum mismatch"
  fi
}

command -v curl >/dev/null || die "curl is required"
command -v tar >/dev/null || die "tar is required"

case "$(uname -s)/$(uname -m)" in
  Linux/x86_64)
    PLATFORM="linux-x86_64"
    SERVICE_MANAGER="systemd"
    SERVICE_NAME="dala"
    SERVICE_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
    command -v systemctl >/dev/null || die "systemd (systemctl --user) is required"
    ;;
  Darwin/arm64)
    PLATFORM="macos-arm64"
    SERVICE_MANAGER="launchd"
    SERVICE_NAME="com.manjialin.dala"
    SERVICE_DIR="$HOME/Library/LaunchAgents"
    command -v launchctl >/dev/null || die "launchctl is required"
    ;;
  *)
    die "no prebuilt release for $(uname -s)/$(uname -m)"
    ;;
esac

# --- resolve version ---------------------------------------------------------
TAG="${1:-}"
if [ -z "$TAG" ]; then
  say "resolving latest release of $REPO"
  # Skip client-v* tags: the repo also publishes desktop-client releases.
  TAG=$(curl -fsSL "https://api.github.com/repos/$REPO/releases?per_page=15" |
    grep '"tag_name"' | cut -d'"' -f4 | grep -m1 '^v[0-9]') || true
  [ -n "$TAG" ] || die "could not resolve the latest release (does $REPO have releases?)"
fi
ASSET="dala-$TAG-$PLATFORM.tar.gz"
URL="https://github.com/$REPO/releases/download/$TAG/$ASSET"
DEST="$ROOT/versions/$TAG"

# --- download + unpack -------------------------------------------------------
if [ -x "$DEST/bin/dala" ]; then
  say "$TAG already downloaded"
else
  say "downloading $ASSET"
  TMP=$(mktemp -d)
  trap 'rm -rf "$TMP"' EXIT
  curl -fSL --progress-bar -o "$TMP/$ASSET" "$URL"
  curl -fsSL -o "$TMP/$ASSET.sha256" "$URL.sha256" 2>/dev/null ||
    die "could not download checksum for $ASSET"
  verify_checksum "$TMP/$ASSET.sha256" "$TMP/$ASSET" "$ASSET"
  say "checksum ok"
  mkdir -p "$DEST"
  tar -xzf "$TMP/$ASSET" -C "$DEST"
fi

# --- configuration (first install only) --------------------------------------
# Configuration lives in a FILE, not environment variables: the service
# process then carries no dala-specific environment, so nothing can leak
# into the shells it spawns. Secrets are generated by the server itself on
# first boot (persisted 0600 at $DATA_DIR/secrets.json).
mkdir -p "$DATA_DIR" "$CONFIG_DIR" "$SERVICE_DIR"
if [ -f "$ENV_FILE" ] && [ ! -f "$CONFIG_FILE" ]; then
  die "legacy $ENV_FILE detected - migrate first (one command, reversible):
  curl -fsSL https://raw.githubusercontent.com/$REPO/main/migrate-config.sh | bash
then re-run this installer"
fi
if [ ! -f "$CONFIG_FILE" ]; then
  say "writing $CONFIG_FILE"
  cat > "$CONFIG_FILE" <<CFGEOF
{
  // Dala server configuration. Restart the service after editing.
  "server": true,
  "port": $PORT,
  // Loopback only by default. LAN access: "0.0.0.0" (then enable auth below!).
  "listenIp": "127.0.0.1",
  "host": "localhost",
  // Reached from other machines? Keep false, or set host + true behind a
  // reverse proxy.
  "checkOrigin": false,
$( [ "$DATA_DIR" != "$HOME/.local/share/dala" ] && printf '  "dataDir": "%s",' "$DATA_DIR" )
  // Install location - also the switch that enables the in-app updater.
  "releaseRoot": "$ROOT",
$( { [ "$SERVICE_NAME" != "dala" ] && [ "$SERVICE_NAME" != "com.manjialin.dala" ]; } && printf '  "serviceName": "%s",' "$SERVICE_NAME" )
  // Optional login (default: open, local use):
  //   "auth": { "enabled": true, "users": "you@example.com:yourpassword" }
  // auth.users is BOOTSTRAP-ONLY - the account is created on first boot;
  // REMOVE it afterwards so the plaintext password does not linger here.
  // Forgot the password? Re-add users plus "usersReset": true for one
  // boot, then remove both.
  "auth": { "enabled": false },
}
CFGEOF
  chmod 600 "$CONFIG_FILE"
else
  say "keeping existing $CONFIG_FILE"
fi

# --- service -----------------------------------------------------------------
ln -sfn "$DEST" "$ROOT/current"

if [ "$SERVICE_MANAGER" = "systemd" ]; then
  say "installing systemd user service"
  cat > "$SERVICE_DIR/$SERVICE_NAME.service" <<EOF
[Unit]
Description=Dala terminal server
After=network.target

[Service]
Type=exec
ExecStartPre=$ROOT/current/bin/dala eval "Dala.Release.migrate()"
ExecStart=$ROOT/current/bin/dala start
ExecStop=$ROOT/current/bin/dala stop
# Only the BEAM dies on restart; detached PTY holders keep shells alive.
KillMode=process
Restart=on-failure
RestartSec=2

[Install]
WantedBy=default.target
EOF

  systemctl --user daemon-reload
  systemctl --user enable "$SERVICE_NAME" >/dev/null 2>&1 || true
  say "starting $SERVICE_NAME ($TAG)"
  systemctl --user restart "$SERVICE_NAME"
  loginctl enable-linger "$USER" 2>/dev/null || true
else
  say "installing launchd user service"
  RUNNER="$ROOT/run-dala"
  PLIST="$SERVICE_DIR/$SERVICE_NAME.plist"
  cat > "$RUNNER" <<EOF
#!/usr/bin/env bash
set -euo pipefail
if [ -x /usr/libexec/path_helper ]; then
  eval "\$(/usr/libexec/path_helper -s)"
fi
"$ROOT/current/bin/dala" eval "Dala.Release.migrate()"
exec "$ROOT/current/bin/dala" start
EOF
  chmod 700 "$RUNNER"

  cat > "$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>$SERVICE_NAME</string>
  <key>ProgramArguments</key>
  <array><string>$RUNNER</string></array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key>
  <dict><key>SuccessfulExit</key><false/></dict>
  <key>ThrottleInterval</key><integer>2</integer>
  <key>WorkingDirectory</key><string>$HOME</string>
  <key>StandardOutPath</key><string>$DATA_DIR/dala.stdout.log</string>
  <key>StandardErrorPath</key><string>$DATA_DIR/dala.stderr.log</string>
</dict>
</plist>
EOF

  DOMAIN="gui/$(id -u)"
  launchctl bootout "$DOMAIN/$SERVICE_NAME" 2>/dev/null || true
  launchctl bootstrap "$DOMAIN" "$PLIST"
  launchctl enable "$DOMAIN/$SERVICE_NAME" 2>/dev/null || true
  say "starting $SERVICE_NAME ($TAG)"
  launchctl kickstart -k "$DOMAIN/$SERVICE_NAME"
fi

# --- prune old versions (keep 3) --------------------------------------------
ls -1dt "$ROOT"/versions/* 2>/dev/null | tail -n +4 | while read -r old; do
  [ "$old" = "$DEST" ] && continue
  say "pruning $(basename "$old")"
  rm -rf "$old"
done

# --- health check ------------------------------------------------------------
PORT_NOW=$(grep -oE '"port"[[:space:]]*:[[:space:]]*[0-9]+' "$CONFIG_FILE" | grep -oE '[0-9]+' | head -1)
PORT_NOW="${PORT_NOW:-$PORT}"
ATTEMPT=0
while [ "$ATTEMPT" -lt 30 ]; do
  if curl -fso /dev/null "http://localhost:$PORT_NOW"; then
    say "dala $TAG is running: http://localhost:$PORT_NOW"
    exit 0
  fi
  ATTEMPT=$((ATTEMPT + 1))
  sleep 1
done

if [ "$SERVICE_MANAGER" = "systemd" ]; then
  die "service did not become healthy - check: journalctl --user -u $SERVICE_NAME -n 50"
else
  die "service did not become healthy - check: tail -n 50 $DATA_DIR/dala.stderr.log"
fi
