defmodule Dala.Repo.Migrations.AddPromptOptimizerSettings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:prompt_optimizer_settings, primary_key: false) do
      add :user_id,
          references(:users,
            column: :id,
            name: "prompt_optimizer_settings_user_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          )

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :api_key, :text
      add :prompt, :text, null: false
      add :model, :text, null: false
      add :endpoint, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `prompt_optimizer_settings` table without the `prompt_optimizer_settings_user_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:prompt_optimizer_settings)
  end
end
