defmodule Dala.Repo.Migrations.AddSessionPosition do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`,
  EXCEPT for the backfill `execute` in `up/0`, which is hand-written:
  existing sessions get positions 1.0..n in insertion order so the sidebar
  keeps its familiar order on first boot after the upgrade. Regenerating
  migrations must not drop it.
  """

  use Ecto.Migration

  def up do
    alter table(:terminal_sessions) do
      add :position, :float, null: false, default: 0.0
    end

    # Backfill: existing sessions keep their insertion order (1.0 .. n).
    execute """
    UPDATE terminal_sessions SET position = (
      SELECT COUNT(*) FROM terminal_sessions AS earlier
      WHERE earlier.inserted_at < terminal_sessions.inserted_at
         OR (earlier.inserted_at = terminal_sessions.inserted_at
             AND earlier.id <= terminal_sessions.id)
    )
    """
  end

  def down do
    alter table(:terminal_sessions) do
      remove :position
    end
  end
end
