defmodule Dala.Repo.Migrations.EphemeralQuickShells do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:terminal_sessions) do
      add :ephemeral, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:terminal_sessions) do
      remove :ephemeral
    end
  end
end
