defmodule Dala.Repo.Migrations.SessionGroup do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:terminal_sessions) do
      add :group, :text
    end
  end

  def down do
    alter table(:terminal_sessions) do
      remove :group
    end
  end
end
