defmodule Dala.Repo.Migrations.PromptStash do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:prompt_stash, primary_key: false) do
      add :user_id,
          references(:users,
            column: :id,
            name: "prompt_stash_user_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          )

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :owner_id, :uuid, null: false
      add :used_at, :utc_datetime_usec
      add :status, :text, null: false
      add :content, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `prompt_stash` table without the `prompt_stash_user_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:prompt_stash)
  end
end
