defmodule Dala.Repo.Migrations.StripEmailAuthFlows do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :hashed_password, :text
    end
  end

  def down do
    alter table(:users) do
      remove :hashed_password
    end
  end
end
