defmodule Dala.Repo.Migrations.CustomThemes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:custom_themes, primary_key: false) do
      add :user_id,
          references(:users,
            column: :id,
            name: "custom_themes_user_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          )

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :tokens, :map, null: false
      add :builtin, :boolean, null: false
      add :base, :text, null: false
      add :name, :text, null: false
      add :owner_id, :uuid, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:custom_themes, [:owner_id, :name],
             name: "custom_themes_unique_name_per_owner_index"
           )
  end

  def down do
    drop_if_exists unique_index(:custom_themes, [:owner_id, :name],
                     name: "custom_themes_unique_name_per_owner_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `custom_themes` table without the `custom_themes_user_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:custom_themes)
  end
end
