defmodule Dala.Repo.Migrations.AddMcpTerminalAccess do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:mcp_config) do
      add :terminal_read, :boolean, null: false, default: false
      add :terminal_control, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:mcp_config) do
      remove :terminal_control
      remove :terminal_read
    end
  end
end
