defmodule Dala.Repo.Migrations.SizeOwnerDevice do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:terminal_sessions) do
      add :size_owner_device, :text
    end
  end

  def down do
    alter table(:terminal_sessions) do
      remove :size_owner_device
    end
  end
end
