defmodule Dala.Repo.Migrations.AddAttachedShells do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:terminal_sessions) do
      add :parent_id, :uuid
    end
  end

  def down do
    alter table(:terminal_sessions) do
      remove :parent_id
    end
  end
end
