defmodule Dala.Repo.Migrations.AddTerminalSessions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:terminal_sessions, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :scrollback_limit, :bigint, null: false
      add :exit_code, :bigint
      add :status, :text, null: false
      add :cwd, :text, null: false
      add :shell, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop table(:terminal_sessions)
  end
end
